# Generated by Django 4.1 on 2022-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parsed_answer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
