# Generated by Django 4.1 on 2022-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_questions_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdialog',
            name='parsed_answer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
