# Generated by Django 4.1 on 2022-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_parsed_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parsed_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
